"""
Django settings for purchase_order project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "127.0.0.1:8080")

# Add to settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEBUG = True  # Should be True during development

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0fliu9^@ym@*a9!e2(+p2j!op8!8$5mktc!$#wo5zgd@7cm(zd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['192.168.0.129', 'localhost', '127.0.0.1', 'web']

# SESSIONS
SESSION_COOKIE_AGE = 1800  # 30 minutes (in seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser closes
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Protect against CSRF attacks



#EMAIL CONFIG 

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development (emails will be printed to the console)
# For production, use an SMTP backend:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # Outlook SMTP server
EMAIL_PORT = 587  # Outlook SMTP port (TLS)
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'amanda@corpus.co.zm'  # Your Outlook email address
EMAIL_HOST_PASSWORD = 'Corpus2024!'  # Your Outlook password or app password

#ALLAUTH SETTINGS
ACCOUNT_SESSION_REMEMBER = None  # Don't extend session duration if "Remember Me" is checked
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[JurisPO] '
ACCOUNT_EMAIL_REQUIRED = True  # Require email for signup
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Send a verification email
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Use email for authentication
ACCOUNT_UNIQUE_EMAIL = True  # Ensure emails are unique
ACCOUNT_SIGNUP_REDIRECT_URL = '/create/'
LOGIN_URL = '/accounts/login/'  # Default allauth login URL (fallback if needed)
LOGIN_REDIRECT_URL = '/create/'  # Redirect after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to login page after logout
SITE_ID = 1
SITE_NAME = "JurisPO"  # Overrides 'example.com'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Fix deprecated settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Authentication Backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

#API KEY
EXCHANGE_RATE_API_KEY = '4af2912fe8ab51d42219c8a2'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # For human-readable dates
    'orders',
    'django.contrib.sites',  # Required for allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add this line
]

ROOT_URLCONF = 'purchase_order.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'purchase_order.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'purchase_order_db'),
        'USER': os.environ.get('DB_USER', 'sup3rab3'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Sup3r@dmin_'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # /app/staticfiles for collected files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'purchase_order', 'static'),  # /app/purchase_order/static for development files
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py
DEFAULT_FROM_EMAIL = 'amanda@corpus.co.zm'  # Must match EMAIL_HOST_USER
SERVER_EMAIL = 'amanda@corpus.co.zm'  # For error notifications


