# Generated by Django 5.2 on 2025-05-01 14:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'orders_exchangerate',
            },
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('fallback_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallbacks', to='orders.approver')),
            ],
        ),
        migrations.CreateModel(
            name='PettyCashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petty_cash_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.CharField(max_length=255)),
                ('matter_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_legal', models.BooleanField(default=False, help_text='Is this a legal petty cash request?')),
                ('selected_approver_email', models.EmailField(blank=True, help_text='Email of the selected approver', max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('DRPP', 'DRPP'), ('B&F', 'B&F'), ('CA', 'CA'), ('ERI', 'ERI')], help_text='Department for legal petty cash requests', max_length=50, null=True)),
                ('non_legal_approver_email', models.EmailField(blank=True, help_text='Email of the selected approver for non-legal requests', max_length=255, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(default='Not Specified', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('include_vat', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('department', models.CharField(choices=[('HR and Administration', 'HR and Administration'), ('IT', 'IT'), ('Client Care', 'Client Care'), ('Accounts', 'Accounts'), ('Business Development', 'Business Development')], default='HR and Administration', max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD'), ('EUR', 'EUR'), ('RAND', 'RAND')], default='ZMW', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotations/%Y/%m/%d/', verbose_name='Quotation File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SignatoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Finance Manager', 'Finance Manager'), ('General Manager', 'General Manager'), ('Managing Partner', 'Managing Partner'), ('Department Approver', 'Department Approver')], default='Finance Manager', max_length=50)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approval_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('signed_by_name', models.CharField(blank=True, help_text='Name of the approver who signed', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('availability_timeout', models.DurationField(default=datetime.timedelta(days=1))),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.approver')),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to='orders.signatoryapproval')),
                ('petty_cash_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.pettycashrequest')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('min_amount_zmw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount_zmw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approvers', models.ManyToManyField(related_name='thresholds', to='orders.approver')),
            ],
            options={
                'unique_together': {('department', 'min_amount_zmw')},
            },
        ),
    ]
