# Generated by Django 5.2 on 2025-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='currency',
            field=models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD'), ('EUR', 'EUR'), ('ZAR', 'ZAR')], default='ZMW', max_length=10),
        ),
    ]
