# Generated by Django 5.1.7 on 2025-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorder_include_vat_purchaseorder_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
