# Generated by Django 5.1.7 on 2025-03-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_signatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.purchaseorder')),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.signatory')),
            ],
        ),
    ]
