# Generated by Django 5.1.7 on 2025-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_signatoryapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatory',
            name='user',
        ),
        migrations.AddField(
            model_name='signatory',
            name='name',
            field=models.CharField(default='Unknown Signatory', max_length=100),
        ),
        migrations.AddField(
            model_name='signatoryapproval',
            name='approval_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signatoryapproval',
            name='email',
            field=models.EmailField(default='amanda@corpus.co.zm', max_length=254),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
