# Generated by Django 5.1.7 on 2025-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_signatoryapproval_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatoryapproval',
            name='email',
        ),
    ]
