name: CI for Purchase Order App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t sup3rab3/purchase-order-system-web:latest .

    - name: Start services with docker-compose
      run: docker compose up -d

    - name: Test app availability
      run: |
        # Wait for the app to start (give it 10 seconds)
        sleep 10
        curl -f http://localhost:8080  # Fails if the app isn't up

    - name: Stop services
      if: always()
      run: docker compose down --remove-orphans
